image: docker:latest

before_script:
  - echo "(!) Starting process"

after_script:
  - echo "(!) Successfully ran process"

build_stage:
  stage: build
  script:
    - rm -rf ~/.m2/repository/me/pabloestrada/
    # - mvn install -f lib/guice-quartz
    # - mvn install -f lib/guice-quartz

deploy_stage:
  stage: deploy
  script:
    - echo "Do your deploy here"
