image: docker:latest

before_script:
  - echo "(!) Starting process"

after_script:
  - echo "(!) Successfully ran process"

build_ui:
  stage: build
  script:
    - sudo npm install --prefix ui/
    - sudo npm run build --prefix ui/
    - sudo docker build -t persian_ui:latest ui/

build_stage:
  stage: build
  script:
    - sudo echo $'jwt_signing_key=${JWT_SIGNING_KEY}\npersian_service_token={PERSIAN_SERVICE_TOKEN}' > service/.credentials
    - sudo echo $'strava_client_id=${STRAVA_CLIENT_ID}\nstrava_client_secret={STRAVA_CLIENT_SECRET}\nstrava_access_token={STRAVA_ACCESS_TOKEN}\nstrava_refresh_token={STRAVA_REFRESH_TOKEN}' > scheduler/.credentials
    - sudo rm -rf ~/.m2/repository/me/pabloestrada/
    - sh lib/credentials/prod_build-persian.sh
    - sh lib/guice-quartz/prod_build-persian.sh
    - sh lib/persian-jobs/prod_build-persian.sh
    - sh persian-services/exercise-tracker/prod_build-persian.sh
    - mvn clean package -f service
    - mvn clean package -f scheduler
    - sudo docker build -t persian_rest:latest service/
    - sudo docker build -t persian_scheduler:latest scheduler/

deploy_stage:
  stage: deploy
  script:
    - sudo docker ps -q --filter "name=persian_rest" | grep -q . && sudo docker stop persian_rest && sudo docker rm -fv persian_rest
    - sudo docker ps -q --filter "name=persian_ui" | grep -q . && sudo docker stop persian_ui && sudo docker rm -fv persian_ui
    - sudo docker ps -q --filter "name=persian_scheduler" | grep -q . && sudo docker stop persian_scheduler && sudo docker rm -fv persian_scheduler
    - sudo docker ps -q --filter "name=persian_database" | grep -q . && sudo docker stop persian_database && sudo docker rm -fv persian_database
    - sudo docker-compose up -d
