image: docker:latest

before_script:
  - echo "(!) Starting process"

after_script:
  - echo "(!) Successfully ran process"

build_stage:
  stage: build
  script:
    - echo "JWT_SIGNING_KEY=${JWT_SIGNING_KEY}"
    # - sudo rm -rf ~/.m2/repository/me/pabloestrada/
    # - sh lib/credentials/prod_build-persian.sh
    # - sh lib/guice-quartz/prod_build-persian.sh
    # - sh lib/persian-jobs/prod_build-persian.sh
    # - sh persian-services/exercise-tracker/prod_build-persian.sh
    # - mvn clean package -f service
    # - mvn clean package -f scheduler
    # - sudo npm install --prefix ui/
    # - sudo npm run build --prefix ui/
    # - sudo docker-compose build

deploy_stage:
  stage: deploy
  script:
    - sudo docker-compose up
