image: docker:latest

before_script:
  - echo "(!) Starting process"

after_script:
  - echo "(!) Successfully ran process"

build_stage:
  stage: build
  script:
    - mvn dependency:purge-local-repository
    -

deploy_stage:
  stage: deploy
  script:
    - echo "Do your deploy here"
