version: '3'
services:
  rest:
    build:
      context: './service/'
    image: persian_rest:latest
    container_name: persian_rest
    ports:
      - 8080:8080
    networks:
      - persian_net
  scheduler:
    build:
      context: './scheduler/'
    image: persian_scheduler:latest
    container_name: persian_scheduler
    networks:
      - persian_net
  ui:
    build:
      context: './ui/'
    image: persian_ui:latest
    container_name: persian_ui
    ports:
      - 5000:80
    networks:
      - persian_net
  database:
    image: 'mongo:latest'
    container_name: 'persian_database'
    networks:
      - persian_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=persian_admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - persian_volume:/data/db
volumes:
  persian_volume:
    external: true
networks:
  persian_net:
    driver: bridge
