swagger:
  resourcePackage: me.pabloestrada.api
  uriPrefix: '/api'
databaseURI: 'mongodb://localhost:27017/'
environment:
  type: "prod"
  host: "https://pabloestrada.me:8433"
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: ssl/keystore.jks
      keyStorePassword: "#PASSWORD"
      validateCerts: false
